<a href="https://colab.research.google.com/github/Raden2510/scraping-miraj/blob/main/hdm_vision_google_playstore_scrapper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Referensi: https://www.linkedin.com/pulse/how-scrape-google-play-reviews-4-simple-steps-using-python-kundi/

!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.10/dist-packages (1.2.7)

In [6]:
from google_play_scraper import app

import pandas as pd

import numpy as np

In [15]:
# Scrape All available reviews
#(DONT RUN THIS CELL!!! RUN ONLY IF YOU WANT TO SCRAPE ALL AVAILABLE REVIEWS)
#JANGAN DI RUN KODE INI, KECUALI ANDA INGIN SCRAPE SEMUA REVIEWS SEKALIGUS

from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'id.dana',
    sleep_milliseconds=0, # defaults to 0
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT , you can use Sort.NEWEST to get newst reviews
)

KeyboardInterrupt:

In [7]:
#Scrape desired number of reviews
#Run kode ini jika ingin scrape data dengan jumlah tertentu. Ganti (misal, ingin scrape sejumlah 1000, maka ganti kode , count = 1000 )

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'id.dana',
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT you can use Sort.NEWEST to get newst reviews
    count=100, # defaults to 100
    filter_score_with=None # defaults to None(means all score) Use 1 or 2 or 3 or 4 or 5 to select certain score
)

In [8]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,ebdadd0a-449a-4c44-a74d-dc82cac55a3e,Roby Sucaksono,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus ini aplikasinya,5,0,None,2025-01-12 15:15:07,None,NaT,None
1,daae2eb8-c8ba-4f65-b59c-0d7404dbbcf9,Achmad Ramli,https://play-lh.googleusercontent.com/a-/ALV-U...,Sangat membanbtu.tp sekarang saya ko g ada men...,4,0,2.71.1,2025-01-12 15:12:32,None,NaT,2.71.1
2,41517679-a431-4e66-a413-5900123fdb88,Aimar Arya sptra,https://play-lh.googleusercontent.com/a-/ALV-U...,Aman aman saja,4,0,2.71.1,2025-01-12 15:11:53,None,NaT,2.71.1
3,e7d21a42-f806-403d-8285-b16a9d0beb52,Holland transfpot,https://play-lh.googleusercontent.com/a/ACg8oc...,Kenapa ko belum ad paylater nya,5,0,2.71.1,2025-01-12 15:11:52,None,NaT,2.71.1
4,5f098356-6749-40de-8db1-830f46d1b0e1,Kasim Bao,https://play-lh.googleusercontent.com/a/ACg8oc...,Oke,5,0,2.71.1,2025-01-12 15:11:38,None,NaT,2.71.1

In [9]:
len(df_busu.index) #count the number of data we got

100

In [10]:
df_busu[['userName', 'score','at', 'content']].head()  #preview userName, rating, date-time, and reviews only

,userName,score,at,content
0,Roby Sucaksono,5,2025-01-12 15:15:07,bagus ini aplikasinya
1,Achmad Ramli,4,2025-01-12 15:12:32,Sangat membanbtu.tp sekarang saya ko g ada men...
2,Aimar Arya sptra,4,2025-01-12 15:11:53,Aman aman saja
3,Holland transfpot,5,2025-01-12 15:11:52,Kenapa ko belum ad paylater nya
4,Kasim Bao,5,2025-01-12 15:11:38,Oke

In [11]:
#Run This Code to Sort the Data By Date

new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) #Sort by Newst, change to True if you want to sort by Oldest.
sorted_df.head()

,userName,score,at,content
0,Roby Sucaksono,5,2025-01-12 15:15:07,bagus ini aplikasinya
1,Achmad Ramli,4,2025-01-12 15:12:32,Sangat membanbtu.tp sekarang saya ko g ada men...
2,Aimar Arya sptra,4,2025-01-12 15:11:53,Aman aman saja
3,Holland transfpot,5,2025-01-12 15:11:52,Kenapa ko belum ad paylater nya
4,Kasim Bao,5,2025-01-12 15:11:38,Oke

In [12]:
my_df = sorted_df[['userName', 'score','at', 'content']] #get userName, rating, date-time, and reviews only

In [13]:
my_df.head()

,userName,score,at,content
0,Roby Sucaksono,5,2025-01-12 15:15:07,bagus ini aplikasinya
1,Achmad Ramli,4,2025-01-12 15:12:32,Sangat membanbtu.tp sekarang saya ko g ada men...
2,Aimar Arya sptra,4,2025-01-12 15:11:53,Aman aman saja
3,Holland transfpot,5,2025-01-12 15:11:52,Kenapa ko belum ad paylater nya
4,Kasim Bao,5,2025-01-12 15:11:38,Oke

In [14]:
my_df.to_csv("scrapped_data.csv", index = False)  #Save the file as CSV , to download: click the folder icon on the left. the csv file should be there.